name: Daurnimator's Hovel
description: A place for thoughts, rants and progress reports
url: https://daurnimator.github.io
twitter:
  username: daurnimator

paginate: 5
permalink: /post/:year/:month/:day/:title/

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

feed:
  path: rss
