name: Daurnimator's Hovel
description: A place for thoughts, rants and progress reports
url: https://daurnimator.github.io
twitter:
  username: daurnimator

paginate: 5

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

feed:
  path: rss
